[2025-05-15T10:41:58.890+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:41:46.017029+00:00 [queued]>
[2025-05-15T10:41:58.896+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:41:46.017029+00:00 [queued]>
[2025-05-15T10:41:58.896+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:41:58.896+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:41:58.897+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:41:58.907+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:41:46.017029+00:00
[2025-05-15T10:41:58.911+0000] {standard_task_runner.py:55} INFO - Started process 197 to run task
[2025-05-15T10:41:58.913+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:41:46.017029+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmplsl3qfd0']
[2025-05-15T10:41:58.914+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask run_dbt_transforms
[2025-05-15T10:41:58.953+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:41:46.017029+00:00 [running]> on host 5d3c8421ca00
[2025-05-15T10:41:59.092+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:41:46.017029+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:41:46.017029+00:00
[2025-05-15T10:41:59.094+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:41:59.094+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /dbt/sales_project --profiles-dir /opt/***/dbt_profiles']
[2025-05-15T10:41:59.103+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:41:59.104+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-05-15T10:41:59.104+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-15T10:41:59.110+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-15T10:41:59.112+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T104146, start_date=20250515T104158, end_date=20250515T104159
[2025-05-15T10:41:59.122+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 127.; 197)
[2025-05-15T10:41:59.165+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:41:59.188+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
