[2025-05-15T10:34:25.351+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:34:12.696817+00:00 [queued]>
[2025-05-15T10:34:25.357+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:34:12.696817+00:00 [queued]>
[2025-05-15T10:34:25.357+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:34:25.358+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:34:25.358+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:34:25.370+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:34:12.696817+00:00
[2025-05-15T10:34:25.374+0000] {standard_task_runner.py:55} INFO - Started process 276 to run task
[2025-05-15T10:34:25.375+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:34:12.696817+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmp1supt_vx']
[2025-05-15T10:34:25.377+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask run_dbt_transforms
[2025-05-15T10:34:25.416+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:34:12.696817+00:00 [running]> on host 93d8d3a43577
[2025-05-15T10:34:25.555+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:34:12.696817+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:34:12.696817+00:00
[2025-05-15T10:34:25.555+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:34:25.556+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/sales_project && dbt run']
[2025-05-15T10:34:25.563+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:34:27.135+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2025-05-15T10:34:27.135+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2025-05-15T10:34:27.136+0000] {subprocess.py:93} INFO - 
[2025-05-15T10:34:27.136+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/home/***/.dbt' does not exist.
[2025-05-15T10:34:27.210+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-15T10:34:27.217+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-15T10:34:27.220+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T103412, start_date=20250515T103425, end_date=20250515T103427
[2025-05-15T10:34:27.232+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 2.; 276)
[2025-05-15T10:34:27.274+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:34:27.284+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
