[2025-05-15T10:43:27.587+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:43:14.947328+00:00 [queued]>
[2025-05-15T10:43:27.593+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:43:14.947328+00:00 [queued]>
[2025-05-15T10:43:27.594+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:43:27.594+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:43:27.594+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:43:27.605+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:43:14.947328+00:00
[2025-05-15T10:43:27.610+0000] {standard_task_runner.py:55} INFO - Started process 263 to run task
[2025-05-15T10:43:27.611+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:43:14.947328+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmpp9ghx9z1']
[2025-05-15T10:43:27.612+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask run_dbt_transforms
[2025-05-15T10:43:27.651+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:43:14.947328+00:00 [running]> on host 5d3c8421ca00
[2025-05-15T10:43:27.800+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:43:14.947328+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:43:14.947328+00:00
[2025-05-15T10:43:27.801+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:43:27.801+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /dbt/sales_project --profiles-dir /opt/***/dbt_profiles']
[2025-05-15T10:43:27.808+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:43:29.358+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2025-05-15T10:43:29.359+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2025-05-15T10:43:29.359+0000] {subprocess.py:93} INFO - 
[2025-05-15T10:43:29.359+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/dbt_profiles' does not exist.
[2025-05-15T10:43:29.434+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-15T10:43:29.441+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-15T10:43:29.443+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T104314, start_date=20250515T104327, end_date=20250515T104329
[2025-05-15T10:43:29.456+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 48 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 2.; 263)
[2025-05-15T10:43:29.468+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:43:29.479+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
