[2025-05-15T10:29:45.185+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:29:31.814738+00:00 [queued]>
[2025-05-15T10:29:45.191+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:29:31.814738+00:00 [queued]>
[2025-05-15T10:29:45.191+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:29:45.192+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:29:45.192+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:29:45.202+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:29:31.814738+00:00
[2025-05-15T10:29:45.206+0000] {standard_task_runner.py:55} INFO - Started process 491 to run task
[2025-05-15T10:29:45.208+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:29:31.814738+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmpyy9c04te']
[2025-05-15T10:29:45.209+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask run_dbt_transforms
[2025-05-15T10:29:45.247+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:29:31.814738+00:00 [running]> on host 92d0d3de5da6
[2025-05-15T10:29:45.378+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:29:31.814738+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:29:31.814738+00:00
[2025-05-15T10:29:45.379+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:29:45.380+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/sales_project && dbt run']
[2025-05-15T10:29:45.386+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:29:45.392+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /dbt/sales_project: No such file or directory
[2025-05-15T10:29:45.392+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-15T10:29:45.399+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-15T10:29:45.401+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T102931, start_date=20250515T102945, end_date=20250515T102945
[2025-05-15T10:29:45.410+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 31 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 1.; 491)
[2025-05-15T10:29:45.420+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:29:45.431+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
