[2025-05-15T13:26:08.871+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt manual__2025-05-15T13:25:16.342201+00:00 [queued]>
[2025-05-15T13:26:08.878+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt manual__2025-05-15T13:25:16.342201+00:00 [queued]>
[2025-05-15T13:26:08.879+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T13:26:08.879+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T13:26:08.879+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T13:26:08.890+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt> on 2025-05-15 13:25:16.342201+00:00
[2025-05-15T13:26:08.893+0000] {standard_task_runner.py:55} INFO - Started process 224 to run task
[2025-05-15T13:26:08.895+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt', 'manual__2025-05-15T13:25:16.342201+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmpr57puu39']
[2025-05-15T13:26:08.897+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask run_dbt
[2025-05-15T13:26:08.935+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt manual__2025-05-15T13:25:16.342201+00:00 [running]> on host 468228cdb93b
[2025-05-15T13:26:09.075+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T13:25:16.342201+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T13:25:16.342201+00:00
[2025-05-15T13:26:09.076+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T13:26:09.077+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --profiles-dir /usr/app/dbt_project --project-dir /usr/app/dbt_project']
[2025-05-15T13:26:09.083+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T13:26:09.083+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-05-15T13:26:09.084+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-15T13:26:09.090+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-15T13:26:09.093+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt, execution_date=20250515T132516, start_date=20250515T132608, end_date=20250515T132609
[2025-05-15T13:26:09.101+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task run_dbt (Bash command failed. The command returned a non-zero exit code 127.; 224)
[2025-05-15T13:26:09.147+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T13:26:09.158+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
