[2025-05-15T10:39:08.088+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:38:55.131535+00:00 [queued]>
[2025-05-15T10:39:08.094+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:38:55.131535+00:00 [queued]>
[2025-05-15T10:39:08.095+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:39:08.095+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:39:08.095+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:39:08.106+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:38:55.131535+00:00
[2025-05-15T10:39:08.111+0000] {standard_task_runner.py:55} INFO - Started process 197 to run task
[2025-05-15T10:39:08.113+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:38:55.131535+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmpqioh5ka_']
[2025-05-15T10:39:08.114+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask run_dbt_transforms
[2025-05-15T10:39:08.157+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:38:55.131535+00:00 [running]> on host 2e82bc4eda91
[2025-05-15T10:39:08.294+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:38:55.131535+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:38:55.131535+00:00
[2025-05-15T10:39:08.295+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:39:08.295+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/sales_project && dbt run']
[2025-05-15T10:39:08.302+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:39:08.304+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-05-15T10:39:08.304+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-15T10:39:08.310+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-15T10:39:08.312+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T103855, start_date=20250515T103908, end_date=20250515T103908
[2025-05-15T10:39:08.321+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 41 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 127.; 197)
[2025-05-15T10:39:08.365+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:39:08.389+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
