[2025-05-15T10:32:12.211+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:31:59.084813+00:00 [queued]>
[2025-05-15T10:32:12.217+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:31:59.084813+00:00 [queued]>
[2025-05-15T10:32:12.217+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:32:12.217+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:32:12.217+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:32:12.227+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:31:59.084813+00:00
[2025-05-15T10:32:12.230+0000] {standard_task_runner.py:55} INFO - Started process 197 to run task
[2025-05-15T10:32:12.232+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:31:59.084813+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmpjrj93pcp']
[2025-05-15T10:32:12.233+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask run_dbt_transforms
[2025-05-15T10:32:12.271+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:31:59.084813+00:00 [running]> on host 93d8d3a43577
[2025-05-15T10:32:12.405+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:31:59.084813+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:31:59.084813+00:00
[2025-05-15T10:32:12.406+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:32:12.406+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/sales_project && dbt run']
[2025-05-15T10:32:12.414+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:32:12.418+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-05-15T10:32:12.419+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-15T10:32:12.427+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-15T10:32:12.430+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T103159, start_date=20250515T103212, end_date=20250515T103212
[2025-05-15T10:32:12.442+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 34 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 127.; 197)
[2025-05-15T10:32:12.484+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:32:12.515+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
