[2025-05-15T10:59:45.796+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:59:33.187310+00:00 [queued]>
[2025-05-15T10:59:45.803+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:59:33.187310+00:00 [queued]>
[2025-05-15T10:59:45.803+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:59:45.804+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:59:45.804+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:59:45.814+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:59:33.187310+00:00
[2025-05-15T10:59:45.817+0000] {standard_task_runner.py:55} INFO - Started process 203 to run task
[2025-05-15T10:59:45.819+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:59:33.187310+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmpz6p8zh0j']
[2025-05-15T10:59:45.820+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask run_dbt_transforms
[2025-05-15T10:59:45.859+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:59:33.187310+00:00 [running]> on host a4658e82a8dd
[2025-05-15T10:59:45.997+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:59:33.187310+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:59:33.187310+00:00
[2025-05-15T10:59:45.998+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:59:45.999+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run --rm -v $(pwd)/dbt/sales_project:/dbt/sales_project -v $(pwd)/dbt_profiles:/root/.dbt --network epsi_dataops_network monimage/dbt:latest dbt run --profiles-dir /root/.dbt -project-dir /dbt/sales_project']
[2025-05-15T10:59:46.005+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:59:46.026+0000] {subprocess.py:93} INFO - Unable to find image 'monimage/dbt:latest' locally
[2025-05-15T10:59:46.715+0000] {subprocess.py:93} INFO - docker: Error response from daemon: pull access denied for monimage/dbt, repository does not exist or may require 'docker login'.
[2025-05-15T10:59:46.717+0000] {subprocess.py:93} INFO - See 'docker run --help'.
[2025-05-15T10:59:46.719+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2025-05-15T10:59:46.732+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-05-15T10:59:46.735+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T105933, start_date=20250515T105945, end_date=20250515T105946
[2025-05-15T10:59:46.745+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 55 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 125.; 203)
[2025-05-15T10:59:46.755+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:59:46.769+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
