[2025-05-15T10:57:35.071+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:57:21.799876+00:00 [queued]>
[2025-05-15T10:57:35.077+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:57:21.799876+00:00 [queued]>
[2025-05-15T10:57:35.078+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:57:35.078+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:57:35.078+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:57:35.088+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:57:21.799876+00:00
[2025-05-15T10:57:35.092+0000] {standard_task_runner.py:55} INFO - Started process 203 to run task
[2025-05-15T10:57:35.094+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:57:21.799876+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmptgdwy1eg']
[2025-05-15T10:57:35.095+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask run_dbt_transforms
[2025-05-15T10:57:35.132+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:57:21.799876+00:00 [running]> on host 8554c1484d9e
[2025-05-15T10:57:35.261+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:57:21.799876+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:57:21.799876+00:00
[2025-05-15T10:57:35.265+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:57:35.266+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run --rm -v $(pwd)/dbt/sales_project:/dbt/sales_project -v $(pwd)/dbt_profiles:/root/.dbt --network epsi_dataops_network monimage/dbt:latest dbt run --profiles-dir /root/.dbt -project-dir /dbt/sales_project']
[2025-05-15T10:57:35.274+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:57:35.352+0000] {subprocess.py:93} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-05-15T10:57:35.353+0000] {subprocess.py:93} INFO - See 'docker run --help'.
[2025-05-15T10:57:35.353+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2025-05-15T10:57:35.360+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-05-15T10:57:35.365+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T105721, start_date=20250515T105735, end_date=20250515T105735
[2025-05-15T10:57:35.375+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 52 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 125.; 203)
[2025-05-15T10:57:35.386+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:57:35.397+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
