[2025-05-15T10:41:03.256+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:40:50.027291+00:00 [queued]>
[2025-05-15T10:41:03.263+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:40:50.027291+00:00 [queued]>
[2025-05-15T10:41:03.263+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:41:03.263+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-05-15T10:41:03.263+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-15T10:41:03.273+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): run_dbt_transforms> on 2025-05-15 10:40:50.027291+00:00
[2025-05-15T10:41:03.278+0000] {standard_task_runner.py:55} INFO - Started process 228 to run task
[2025-05-15T10:41:03.279+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_ingestion', 'run_dbt_transforms', 'manual__2025-05-15T10:40:50.027291+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/upload_csv_to_postgres.py', '--cfg-path', '/tmp/tmps3485kak']
[2025-05-15T10:41:03.280+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask run_dbt_transforms
[2025-05-15T10:41:03.318+0000] {task_command.py:389} INFO - Running <TaskInstance: sales_ingestion.run_dbt_transforms manual__2025-05-15T10:40:50.027291+00:00 [running]> on host 2e82bc4eda91
[2025-05-15T10:41:03.484+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sales_ingestion
AIRFLOW_CTX_TASK_ID=run_dbt_transforms
AIRFLOW_CTX_EXECUTION_DATE=2025-05-15T10:40:50.027291+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-15T10:40:50.027291+00:00
[2025-05-15T10:41:03.485+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-05-15T10:41:03.486+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir /dbt/sales_project --profiles-dir /opt/***/dbt_profiles']
[2025-05-15T10:41:03.493+0000] {subprocess.py:86} INFO - Output:
[2025-05-15T10:41:03.494+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-05-15T10:41:03.494+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-15T10:41:03.503+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-15T10:41:03.506+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=sales_ingestion, task_id=run_dbt_transforms, execution_date=20250515T104050, start_date=20250515T104103, end_date=20250515T104103
[2025-05-15T10:41:03.515+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 43 for task run_dbt_transforms (Bash command failed. The command returned a non-zero exit code 127.; 228)
[2025-05-15T10:41:03.532+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-05-15T10:41:03.543+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
